// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apple_loc.proto

package com.apple.iphone.services;

public final class LocationsProtos {
	public static final class Request extends
			com.google.protobuf.GeneratedMessage implements RequestOrBuilder {
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.apple.iphone.services.LocationsProtos.RequestOrBuilder {
			private static Builder create() {
				return new Builder();
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_Request_descriptor;
			}

			private int bitField0_;

			// repeated .apple.RequestWLAN wlan = 2;
			private java.util.List<com.apple.iphone.services.LocationsProtos.RequestWLAN> wlan_ = java.util.Collections
					.emptyList();
			private com.google.protobuf.RepeatedFieldBuilder<com.apple.iphone.services.LocationsProtos.RequestWLAN, com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder, com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder> wlanBuilder_;
			// required int32 unknown3 = 3;
			private int unknown3_;

			// required int32 unknown4 = 4;
			private int unknown4_;

			// required string source = 5;
			private java.lang.Object source_ = "";

			// Construct using
			// com.apple.iphone.services.LocationsProtos.Request.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			public Builder addAllWlan(
					java.lang.Iterable<? extends com.apple.iphone.services.LocationsProtos.RequestWLAN> values) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					super.addAll(values, wlan_);
					onChanged();
				} else {
					wlanBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder addWlan(
					com.apple.iphone.services.LocationsProtos.RequestWLAN value) {
				if (wlanBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureWlanIsMutable();
					wlan_.add(value);
					onChanged();
				} else {
					wlanBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addWlan(
					com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder builderForValue) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.add(builderForValue.build());
					onChanged();
				} else {
					wlanBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addWlan(int index,
					com.apple.iphone.services.LocationsProtos.RequestWLAN value) {
				if (wlanBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureWlanIsMutable();
					wlan_.add(index, value);
					onChanged();
				} else {
					wlanBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addWlan(
					int index,
					com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder builderForValue) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.add(index, builderForValue.build());
					onChanged();
				} else {
					wlanBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder addWlanBuilder() {
				return getWlanFieldBuilder().addBuilder(
						com.apple.iphone.services.LocationsProtos.RequestWLAN
								.getDefaultInstance());
			}

			public com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder addWlanBuilder(
					int index) {
				return getWlanFieldBuilder().addBuilder(
						index,
						com.apple.iphone.services.LocationsProtos.RequestWLAN
								.getDefaultInstance());
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.Request build() {
				final com.apple.iphone.services.LocationsProtos.Request result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.apple.iphone.services.LocationsProtos.Request buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				final com.apple.iphone.services.LocationsProtos.Request result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.Request buildPartial() {
				final com.apple.iphone.services.LocationsProtos.Request result = new com.apple.iphone.services.LocationsProtos.Request(
						this);
				final int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (wlanBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						wlan_ = java.util.Collections.unmodifiableList(wlan_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.wlan_ = wlan_;
				} else {
					result.wlan_ = wlanBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000001;
				}
				result.unknown3_ = unknown3_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000002;
				}
				result.unknown4_ = unknown4_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000004;
				}
				result.source_ = source_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clear() {
				super.clear();
				if (wlanBuilder_ == null) {
					wlan_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					wlanBuilder_.clear();
				}
				unknown3_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				unknown4_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				source_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			public Builder clearSource() {
				bitField0_ = (bitField0_ & ~0x00000008);
				source_ = getDefaultInstance().getSource();
				onChanged();
				return this;
			}

			public Builder clearUnknown3() {
				bitField0_ = (bitField0_ & ~0x00000002);
				unknown3_ = 0;
				onChanged();
				return this;
			}

			public Builder clearUnknown4() {
				bitField0_ = (bitField0_ & ~0x00000004);
				unknown4_ = 0;
				onChanged();
				return this;
			}

			public Builder clearWlan() {
				if (wlanBuilder_ == null) {
					wlan_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					wlanBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			private void ensureWlanIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					wlan_ = new java.util.ArrayList<com.apple.iphone.services.LocationsProtos.RequestWLAN>(
							wlan_);
					bitField0_ |= 0x00000001;
				}
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.Request getDefaultInstanceForType() {
				return com.apple.iphone.services.LocationsProtos.Request
						.getDefaultInstance();
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.apple.iphone.services.LocationsProtos.Request
						.getDescriptor();
			}

			@Override
			public String getSource() {
				final java.lang.Object ref = source_;
				if (!(ref instanceof String)) {
					final String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					source_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			@Override
			public int getUnknown3() {
				return unknown3_;
			}

			@Override
			public int getUnknown4() {
				return unknown4_;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.RequestWLAN getWlan(
					int index) {
				if (wlanBuilder_ == null) {
					return wlan_.get(index);
				} else {
					return wlanBuilder_.getMessage(index);
				}
			}

			public com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder getWlanBuilder(
					int index) {
				return getWlanFieldBuilder().getBuilder(index);
			}

			public java.util.List<com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder> getWlanBuilderList() {
				return getWlanFieldBuilder().getBuilderList();
			}

			@Override
			public int getWlanCount() {
				if (wlanBuilder_ == null) {
					return wlan_.size();
				} else {
					return wlanBuilder_.getCount();
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.apple.iphone.services.LocationsProtos.RequestWLAN, com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder, com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder> getWlanFieldBuilder() {
				if (wlanBuilder_ == null) {
					wlanBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.apple.iphone.services.LocationsProtos.RequestWLAN, com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder, com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder>(
							wlan_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					wlan_ = null;
				}
				return wlanBuilder_;
			}

			@Override
			public java.util.List<com.apple.iphone.services.LocationsProtos.RequestWLAN> getWlanList() {
				if (wlanBuilder_ == null) {
					return java.util.Collections.unmodifiableList(wlan_);
				} else {
					return wlanBuilder_.getMessageList();
				}
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder getWlanOrBuilder(
					int index) {
				if (wlanBuilder_ == null) {
					return wlan_.get(index);
				} else {
					return wlanBuilder_.getMessageOrBuilder(index);
				}
			}

			@Override
			public java.util.List<? extends com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder> getWlanOrBuilderList() {
				if (wlanBuilder_ != null) {
					return wlanBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(wlan_);
				}
			}

			@Override
			public boolean hasSource() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			@Override
			public boolean hasUnknown3() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			@Override
			public boolean hasUnknown4() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_Request_fieldAccessorTable;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasUnknown3()) {

					return false;
				}
				if (!hasUnknown4()) {

					return false;
				}
				if (!hasSource()) {

					return false;
				}
				for (int i = 0; i < getWlanCount(); i++) {
					if (!getWlan(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getWlanFieldBuilder();
				}
			}

			public Builder mergeFrom(
					com.apple.iphone.services.LocationsProtos.Request other) {
				if (other == com.apple.iphone.services.LocationsProtos.Request
						.getDefaultInstance()) {
					return this;
				}
				if (wlanBuilder_ == null) {
					if (!other.wlan_.isEmpty()) {
						if (wlan_.isEmpty()) {
							wlan_ = other.wlan_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureWlanIsMutable();
							wlan_.addAll(other.wlan_);
						}
						onChanged();
					}
				} else {
					if (!other.wlan_.isEmpty()) {
						if (wlanBuilder_.isEmpty()) {
							wlanBuilder_.dispose();
							wlanBuilder_ = null;
							wlan_ = other.wlan_;
							bitField0_ = (bitField0_ & ~0x00000001);
							wlanBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getWlanFieldBuilder()
									: null;
						} else {
							wlanBuilder_.addAllMessages(other.wlan_);
						}
					}
				}
				if (other.hasUnknown3()) {
					setUnknown3(other.getUnknown3());
				}
				if (other.hasUnknown4()) {
					setUnknown4(other.getUnknown4());
				}
				if (other.hasSource()) {
					setSource(other.getSource());
				}
				mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				final com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(getUnknownFields());
				while (true) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 18: {
						final com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder subBuilder = com.apple.iphone.services.LocationsProtos.RequestWLAN
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addWlan(subBuilder.buildPartial());
						break;
					}
					case 24: {
						bitField0_ |= 0x00000002;
						unknown3_ = input.readInt32();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000004;
						unknown4_ = input.readInt32();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000008;
						source_ = input.readBytes();
						break;
					}
					}
				}
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.apple.iphone.services.LocationsProtos.Request) {
					return mergeFrom((com.apple.iphone.services.LocationsProtos.Request) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder removeWlan(int index) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.remove(index);
					onChanged();
				} else {
					wlanBuilder_.remove(index);
				}
				return this;
			}

			void setSource(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000008;
				source_ = value;
				onChanged();
			}

			public Builder setSource(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				source_ = value;
				onChanged();
				return this;
			}

			public Builder setUnknown3(int value) {
				bitField0_ |= 0x00000002;
				unknown3_ = value;
				onChanged();
				return this;
			}

			public Builder setUnknown4(int value) {
				bitField0_ |= 0x00000004;
				unknown4_ = value;
				onChanged();
				return this;
			}

			public Builder setWlan(int index,
					com.apple.iphone.services.LocationsProtos.RequestWLAN value) {
				if (wlanBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureWlanIsMutable();
					wlan_.set(index, value);
					onChanged();
				} else {
					wlanBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setWlan(
					int index,
					com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder builderForValue) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.set(index, builderForValue.build());
					onChanged();
				} else {
					wlanBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			// @@protoc_insertion_point(builder_scope:apple.Request)
		}

		private static final Request defaultInstance;

		// repeated .apple.RequestWLAN wlan = 2;
		public static final int WLAN_FIELD_NUMBER = 2;
		// required int32 unknown3 = 3;
		public static final int UNKNOWN3_FIELD_NUMBER = 3;

		// required int32 unknown4 = 4;
		public static final int UNKNOWN4_FIELD_NUMBER = 4;

		// required string source = 5;
		public static final int SOURCE_FIELD_NUMBER = 5;

		public static Request getDefaultInstance() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_Request_descriptor;
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		private byte memoizedIsInitialized = -1;
		private int memoizedSerializedSize = -1;
		private static final long serialVersionUID = 0L;
		static {
			defaultInstance = new Request(true);
			defaultInstance.initFields();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public static Builder newBuilder(
				com.apple.iphone.services.LocationsProtos.Request prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Request parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		private int bitField0_;
		private java.util.List<com.apple.iphone.services.LocationsProtos.RequestWLAN> wlan_;
		private int unknown3_;
		private int unknown4_;

		private java.lang.Object source_;

		private Request(boolean noInit) {
		}

		// Use Request.newBuilder() to construct.
		private Request(Builder builder) {
			super(builder);
		}

		@Override
		public Request getDefaultInstanceForType() {
			return defaultInstance;
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			for (int i = 0; i < wlan_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(2, wlan_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, unknown3_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						4, unknown4_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getSourceBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@Override
		public String getSource() {
			final java.lang.Object ref = source_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					source_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getSourceBytes() {
			final java.lang.Object ref = source_;
			if (ref instanceof String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				source_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		@Override
		public int getUnknown3() {
			return unknown3_;
		}

		@Override
		public int getUnknown4() {
			return unknown4_;
		}

		@Override
		public com.apple.iphone.services.LocationsProtos.RequestWLAN getWlan(
				int index) {
			return wlan_.get(index);
		}

		@Override
		public int getWlanCount() {
			return wlan_.size();
		}

		@Override
		public java.util.List<com.apple.iphone.services.LocationsProtos.RequestWLAN> getWlanList() {
			return wlan_;
		}

		@Override
		public com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder getWlanOrBuilder(
				int index) {
			return wlan_.get(index);
		}

		@Override
		public java.util.List<? extends com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder> getWlanOrBuilderList() {
			return wlan_;
		}

		@Override
		public boolean hasSource() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		@Override
		public boolean hasUnknown3() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		@Override
		public boolean hasUnknown4() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		private void initFields() {
			wlan_ = java.util.Collections.emptyList();
			unknown3_ = 0;
			unknown4_ = 0;
			source_ = "";
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_Request_fieldAccessorTable;
		}

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			if (!hasUnknown3()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasUnknown4()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasSource()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getWlanCount(); i++) {
				if (!getWlan(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < wlan_.size(); i++) {
				output.writeMessage(2, wlan_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(3, unknown3_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(4, unknown4_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(5, getSourceBytes());
			}
			getUnknownFields().writeTo(output);
		}

		// @@protoc_insertion_point(class_scope:apple.Request)
	}

	public interface RequestOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		String getSource();

		int getUnknown3();

		int getUnknown4();

		com.apple.iphone.services.LocationsProtos.RequestWLAN getWlan(int index);

		int getWlanCount();

		// repeated .apple.RequestWLAN wlan = 2;
		java.util.List<com.apple.iphone.services.LocationsProtos.RequestWLAN> getWlanList();

		com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder getWlanOrBuilder(
				int index);

		java.util.List<? extends com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder> getWlanOrBuilderList();

		// required string source = 5;
		boolean hasSource();

		// required int32 unknown3 = 3;
		boolean hasUnknown3();

		// required int32 unknown4 = 4;
		boolean hasUnknown4();
	}

	public static final class RequestWLAN extends
			com.google.protobuf.GeneratedMessage implements
			RequestWLANOrBuilder {
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.apple.iphone.services.LocationsProtos.RequestWLANOrBuilder {
			private static Builder create() {
				return new Builder();
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_RequestWLAN_descriptor;
			}

			private int bitField0_;

			// required string mac = 1;
			private java.lang.Object mac_ = "";

			// Construct using
			// com.apple.iphone.services.LocationsProtos.RequestWLAN.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.RequestWLAN build() {
				final com.apple.iphone.services.LocationsProtos.RequestWLAN result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.apple.iphone.services.LocationsProtos.RequestWLAN buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				final com.apple.iphone.services.LocationsProtos.RequestWLAN result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.RequestWLAN buildPartial() {
				final com.apple.iphone.services.LocationsProtos.RequestWLAN result = new com.apple.iphone.services.LocationsProtos.RequestWLAN(
						this);
				final int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.mac_ = mac_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clear() {
				super.clear();
				mac_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clearMac() {
				bitField0_ = (bitField0_ & ~0x00000001);
				mac_ = getDefaultInstance().getMac();
				onChanged();
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.RequestWLAN getDefaultInstanceForType() {
				return com.apple.iphone.services.LocationsProtos.RequestWLAN
						.getDefaultInstance();
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.apple.iphone.services.LocationsProtos.RequestWLAN
						.getDescriptor();
			}

			@Override
			public String getMac() {
				final java.lang.Object ref = mac_;
				if (!(ref instanceof String)) {
					final String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					mac_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			@Override
			public boolean hasMac() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_RequestWLAN_fieldAccessorTable;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasMac()) {

					return false;
				}
				return true;
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			public Builder mergeFrom(
					com.apple.iphone.services.LocationsProtos.RequestWLAN other) {
				if (other == com.apple.iphone.services.LocationsProtos.RequestWLAN
						.getDefaultInstance()) {
					return this;
				}
				if (other.hasMac()) {
					setMac(other.getMac());
				}
				mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				final com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(getUnknownFields());
				while (true) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						mac_ = input.readBytes();
						break;
					}
					}
				}
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.apple.iphone.services.LocationsProtos.RequestWLAN) {
					return mergeFrom((com.apple.iphone.services.LocationsProtos.RequestWLAN) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			void setMac(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				mac_ = value;
				onChanged();
			}

			public Builder setMac(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				mac_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:apple.RequestWLAN)
		}

		private static final RequestWLAN defaultInstance;

		// required string mac = 1;
		public static final int MAC_FIELD_NUMBER = 1;
		private static final long serialVersionUID = 0L;

		static {
			defaultInstance = new RequestWLAN(true);
			defaultInstance.initFields();
		}

		public static RequestWLAN getDefaultInstance() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_RequestWLAN_descriptor;
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public static Builder newBuilder(
				com.apple.iphone.services.LocationsProtos.RequestWLAN prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.RequestWLAN parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		private int bitField0_;
		private java.lang.Object mac_;

		private byte memoizedIsInitialized = -1;
		private int memoizedSerializedSize = -1;

		private RequestWLAN(boolean noInit) {
		}

		// Use RequestWLAN.newBuilder() to construct.
		private RequestWLAN(Builder builder) {
			super(builder);
		}

		@Override
		public RequestWLAN getDefaultInstanceForType() {
			return defaultInstance;
		}

		@Override
		public String getMac() {
			final java.lang.Object ref = mac_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					mac_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getMacBytes() {
			final java.lang.Object ref = mac_;
			if (ref instanceof String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				mac_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getMacBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@Override
		public boolean hasMac() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		private void initFields() {
			mac_ = "";
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_RequestWLAN_fieldAccessorTable;
		}

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			if (!hasMac()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getMacBytes());
			}
			getUnknownFields().writeTo(output);
		}

		// @@protoc_insertion_point(class_scope:apple.RequestWLAN)
	}

	public interface RequestWLANOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		String getMac();

		// required string mac = 1;
		boolean hasMac();
	}

	public static final class Response extends
			com.google.protobuf.GeneratedMessage implements ResponseOrBuilder {
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.apple.iphone.services.LocationsProtos.ResponseOrBuilder {
			private static Builder create() {
				return new Builder();
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_Response_descriptor;
			}

			private int bitField0_;

			// repeated .apple.ResponseWLAN wlan = 2;
			private java.util.List<com.apple.iphone.services.LocationsProtos.ResponseWLAN> wlan_ = java.util.Collections
					.emptyList();
			private com.google.protobuf.RepeatedFieldBuilder<com.apple.iphone.services.LocationsProtos.ResponseWLAN, com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder, com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder> wlanBuilder_;

			// Construct using
			// com.apple.iphone.services.LocationsProtos.Response.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			public Builder addAllWlan(
					java.lang.Iterable<? extends com.apple.iphone.services.LocationsProtos.ResponseWLAN> values) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					super.addAll(values, wlan_);
					onChanged();
				} else {
					wlanBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder addWlan(
					com.apple.iphone.services.LocationsProtos.ResponseWLAN value) {
				if (wlanBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureWlanIsMutable();
					wlan_.add(value);
					onChanged();
				} else {
					wlanBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addWlan(
					com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder builderForValue) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.add(builderForValue.build());
					onChanged();
				} else {
					wlanBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addWlan(int index,
					com.apple.iphone.services.LocationsProtos.ResponseWLAN value) {
				if (wlanBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureWlanIsMutable();
					wlan_.add(index, value);
					onChanged();
				} else {
					wlanBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addWlan(
					int index,
					com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder builderForValue) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.add(index, builderForValue.build());
					onChanged();
				} else {
					wlanBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder addWlanBuilder() {
				return getWlanFieldBuilder().addBuilder(
						com.apple.iphone.services.LocationsProtos.ResponseWLAN
								.getDefaultInstance());
			}

			public com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder addWlanBuilder(
					int index) {
				return getWlanFieldBuilder().addBuilder(
						index,
						com.apple.iphone.services.LocationsProtos.ResponseWLAN
								.getDefaultInstance());
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.Response build() {
				final com.apple.iphone.services.LocationsProtos.Response result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.apple.iphone.services.LocationsProtos.Response buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				final com.apple.iphone.services.LocationsProtos.Response result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.Response buildPartial() {
				final com.apple.iphone.services.LocationsProtos.Response result = new com.apple.iphone.services.LocationsProtos.Response(
						this);
				final int from_bitField0_ = bitField0_;
				if (wlanBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						wlan_ = java.util.Collections.unmodifiableList(wlan_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.wlan_ = wlan_;
				} else {
					result.wlan_ = wlanBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder clear() {
				super.clear();
				if (wlanBuilder_ == null) {
					wlan_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					wlanBuilder_.clear();
				}
				return this;
			}

			public Builder clearWlan() {
				if (wlanBuilder_ == null) {
					wlan_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					wlanBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			private void ensureWlanIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					wlan_ = new java.util.ArrayList<com.apple.iphone.services.LocationsProtos.ResponseWLAN>(
							wlan_);
					bitField0_ |= 0x00000001;
				}
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.Response getDefaultInstanceForType() {
				return com.apple.iphone.services.LocationsProtos.Response
						.getDefaultInstance();
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.apple.iphone.services.LocationsProtos.Response
						.getDescriptor();
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.ResponseWLAN getWlan(
					int index) {
				if (wlanBuilder_ == null) {
					return wlan_.get(index);
				} else {
					return wlanBuilder_.getMessage(index);
				}
			}

			public com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder getWlanBuilder(
					int index) {
				return getWlanFieldBuilder().getBuilder(index);
			}

			public java.util.List<com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder> getWlanBuilderList() {
				return getWlanFieldBuilder().getBuilderList();
			}

			@Override
			public int getWlanCount() {
				if (wlanBuilder_ == null) {
					return wlan_.size();
				} else {
					return wlanBuilder_.getCount();
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.apple.iphone.services.LocationsProtos.ResponseWLAN, com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder, com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder> getWlanFieldBuilder() {
				if (wlanBuilder_ == null) {
					wlanBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.apple.iphone.services.LocationsProtos.ResponseWLAN, com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder, com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder>(
							wlan_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					wlan_ = null;
				}
				return wlanBuilder_;
			}

			@Override
			public java.util.List<com.apple.iphone.services.LocationsProtos.ResponseWLAN> getWlanList() {
				if (wlanBuilder_ == null) {
					return java.util.Collections.unmodifiableList(wlan_);
				} else {
					return wlanBuilder_.getMessageList();
				}
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder getWlanOrBuilder(
					int index) {
				if (wlanBuilder_ == null) {
					return wlan_.get(index);
				} else {
					return wlanBuilder_.getMessageOrBuilder(index);
				}
			}

			@Override
			public java.util.List<? extends com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder> getWlanOrBuilderList() {
				if (wlanBuilder_ != null) {
					return wlanBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(wlan_);
				}
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_Response_fieldAccessorTable;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getWlanCount(); i++) {
					if (!getWlan(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getWlanFieldBuilder();
				}
			}

			public Builder mergeFrom(
					com.apple.iphone.services.LocationsProtos.Response other) {
				if (other == com.apple.iphone.services.LocationsProtos.Response
						.getDefaultInstance()) {
					return this;
				}
				if (wlanBuilder_ == null) {
					if (!other.wlan_.isEmpty()) {
						if (wlan_.isEmpty()) {
							wlan_ = other.wlan_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureWlanIsMutable();
							wlan_.addAll(other.wlan_);
						}
						onChanged();
					}
				} else {
					if (!other.wlan_.isEmpty()) {
						if (wlanBuilder_.isEmpty()) {
							wlanBuilder_.dispose();
							wlanBuilder_ = null;
							wlan_ = other.wlan_;
							bitField0_ = (bitField0_ & ~0x00000001);
							wlanBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getWlanFieldBuilder()
									: null;
						} else {
							wlanBuilder_.addAllMessages(other.wlan_);
						}
					}
				}
				mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				final com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(getUnknownFields());
				while (true) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 18: {
						final com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder subBuilder = com.apple.iphone.services.LocationsProtos.ResponseWLAN
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addWlan(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.apple.iphone.services.LocationsProtos.Response) {
					return mergeFrom((com.apple.iphone.services.LocationsProtos.Response) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder removeWlan(int index) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.remove(index);
					onChanged();
				} else {
					wlanBuilder_.remove(index);
				}
				return this;
			}

			public Builder setWlan(int index,
					com.apple.iphone.services.LocationsProtos.ResponseWLAN value) {
				if (wlanBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureWlanIsMutable();
					wlan_.set(index, value);
					onChanged();
				} else {
					wlanBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setWlan(
					int index,
					com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder builderForValue) {
				if (wlanBuilder_ == null) {
					ensureWlanIsMutable();
					wlan_.set(index, builderForValue.build());
					onChanged();
				} else {
					wlanBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			// @@protoc_insertion_point(builder_scope:apple.Response)
		}

		private static final Response defaultInstance;

		// repeated .apple.ResponseWLAN wlan = 2;
		public static final int WLAN_FIELD_NUMBER = 2;
		private static final long serialVersionUID = 0L;

		static {
			defaultInstance = new Response(true);
			defaultInstance.initFields();
		}

		public static Response getDefaultInstance() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_Response_descriptor;
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public static Builder newBuilder(
				com.apple.iphone.services.LocationsProtos.Response prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.Response parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		private java.util.List<com.apple.iphone.services.LocationsProtos.ResponseWLAN> wlan_;

		private byte memoizedIsInitialized = -1;
		private int memoizedSerializedSize = -1;

		private Response(boolean noInit) {
		}

		// Use Response.newBuilder() to construct.
		private Response(Builder builder) {
			super(builder);
		}

		@Override
		public Response getDefaultInstanceForType() {
			return defaultInstance;
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			for (int i = 0; i < wlan_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(2, wlan_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@Override
		public com.apple.iphone.services.LocationsProtos.ResponseWLAN getWlan(
				int index) {
			return wlan_.get(index);
		}

		@Override
		public int getWlanCount() {
			return wlan_.size();
		}

		@Override
		public java.util.List<com.apple.iphone.services.LocationsProtos.ResponseWLAN> getWlanList() {
			return wlan_;
		}

		@Override
		public com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder getWlanOrBuilder(
				int index) {
			return wlan_.get(index);
		}

		@Override
		public java.util.List<? extends com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder> getWlanOrBuilderList() {
			return wlan_;
		}

		private void initFields() {
			wlan_ = java.util.Collections.emptyList();
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_Response_fieldAccessorTable;
		}

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			for (int i = 0; i < getWlanCount(); i++) {
				if (!getWlan(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < wlan_.size(); i++) {
				output.writeMessage(2, wlan_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		// @@protoc_insertion_point(class_scope:apple.Response)
	}

	public interface ResponseOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		com.apple.iphone.services.LocationsProtos.ResponseWLAN getWlan(int index);

		int getWlanCount();

		// repeated .apple.ResponseWLAN wlan = 2;
		java.util.List<com.apple.iphone.services.LocationsProtos.ResponseWLAN> getWlanList();

		com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder getWlanOrBuilder(
				int index);

		java.util.List<? extends com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder> getWlanOrBuilderList();
	}

	public static final class ResponseWLAN extends
			com.google.protobuf.GeneratedMessage implements
			ResponseWLANOrBuilder {
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.apple.iphone.services.LocationsProtos.ResponseWLANOrBuilder {
			private static Builder create() {
				return new Builder();
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_ResponseWLAN_descriptor;
			}

			private int bitField0_;

			// required string mac = 1;
			private java.lang.Object mac_ = "";
			// required .apple.WLANLocation location = 2;
			private com.apple.iphone.services.LocationsProtos.WLANLocation location_ = com.apple.iphone.services.LocationsProtos.WLANLocation
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<com.apple.iphone.services.LocationsProtos.WLANLocation, com.apple.iphone.services.LocationsProtos.WLANLocation.Builder, com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder> locationBuilder_;

			// optional int32 channel = 21;
			private int channel_;

			// Construct using
			// com.apple.iphone.services.LocationsProtos.ResponseWLAN.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.ResponseWLAN build() {
				final com.apple.iphone.services.LocationsProtos.ResponseWLAN result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.apple.iphone.services.LocationsProtos.ResponseWLAN buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				final com.apple.iphone.services.LocationsProtos.ResponseWLAN result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.ResponseWLAN buildPartial() {
				final com.apple.iphone.services.LocationsProtos.ResponseWLAN result = new com.apple.iphone.services.LocationsProtos.ResponseWLAN(
						this);
				final int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.mac_ = mac_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				if (locationBuilder_ == null) {
					result.location_ = location_;
				} else {
					result.location_ = locationBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.channel_ = channel_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clear() {
				super.clear();
				mac_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				if (locationBuilder_ == null) {
					location_ = com.apple.iphone.services.LocationsProtos.WLANLocation
							.getDefaultInstance();
				} else {
					locationBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				channel_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clearChannel() {
				bitField0_ = (bitField0_ & ~0x00000004);
				channel_ = 0;
				onChanged();
				return this;
			}

			public Builder clearLocation() {
				if (locationBuilder_ == null) {
					location_ = com.apple.iphone.services.LocationsProtos.WLANLocation
							.getDefaultInstance();
					onChanged();
				} else {
					locationBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clearMac() {
				bitField0_ = (bitField0_ & ~0x00000001);
				mac_ = getDefaultInstance().getMac();
				onChanged();
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public int getChannel() {
				return channel_;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.ResponseWLAN getDefaultInstanceForType() {
				return com.apple.iphone.services.LocationsProtos.ResponseWLAN
						.getDefaultInstance();
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.apple.iphone.services.LocationsProtos.ResponseWLAN
						.getDescriptor();
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.WLANLocation getLocation() {
				if (locationBuilder_ == null) {
					return location_;
				} else {
					return locationBuilder_.getMessage();
				}
			}

			public com.apple.iphone.services.LocationsProtos.WLANLocation.Builder getLocationBuilder() {
				bitField0_ |= 0x00000002;
				onChanged();
				return getLocationFieldBuilder().getBuilder();
			}

			private com.google.protobuf.SingleFieldBuilder<com.apple.iphone.services.LocationsProtos.WLANLocation, com.apple.iphone.services.LocationsProtos.WLANLocation.Builder, com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder> getLocationFieldBuilder() {
				if (locationBuilder_ == null) {
					locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.apple.iphone.services.LocationsProtos.WLANLocation, com.apple.iphone.services.LocationsProtos.WLANLocation.Builder, com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder>(
							location_, getParentForChildren(), isClean());
					location_ = null;
				}
				return locationBuilder_;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder getLocationOrBuilder() {
				if (locationBuilder_ != null) {
					return locationBuilder_.getMessageOrBuilder();
				} else {
					return location_;
				}
			}

			@Override
			public String getMac() {
				final java.lang.Object ref = mac_;
				if (!(ref instanceof String)) {
					final String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					mac_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			@Override
			public boolean hasChannel() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			@Override
			public boolean hasLocation() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			@Override
			public boolean hasMac() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_ResponseWLAN_fieldAccessorTable;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasMac()) {

					return false;
				}
				if (!hasLocation()) {

					return false;
				}
				if (!getLocation().isInitialized()) {

					return false;
				}
				return true;
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getLocationFieldBuilder();
				}
			}

			public Builder mergeFrom(
					com.apple.iphone.services.LocationsProtos.ResponseWLAN other) {
				if (other == com.apple.iphone.services.LocationsProtos.ResponseWLAN
						.getDefaultInstance()) {
					return this;
				}
				if (other.hasMac()) {
					setMac(other.getMac());
				}
				if (other.hasLocation()) {
					mergeLocation(other.getLocation());
				}
				if (other.hasChannel()) {
					setChannel(other.getChannel());
				}
				mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				final com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(getUnknownFields());
				while (true) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						mac_ = input.readBytes();
						break;
					}
					case 18: {
						final com.apple.iphone.services.LocationsProtos.WLANLocation.Builder subBuilder = com.apple.iphone.services.LocationsProtos.WLANLocation
								.newBuilder();
						if (hasLocation()) {
							subBuilder.mergeFrom(getLocation());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setLocation(subBuilder.buildPartial());
						break;
					}
					case 168: {
						bitField0_ |= 0x00000004;
						channel_ = input.readInt32();
						break;
					}
					}
				}
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.apple.iphone.services.LocationsProtos.ResponseWLAN) {
					return mergeFrom((com.apple.iphone.services.LocationsProtos.ResponseWLAN) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeLocation(
					com.apple.iphone.services.LocationsProtos.WLANLocation value) {
				if (locationBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)
							&& location_ != com.apple.iphone.services.LocationsProtos.WLANLocation
									.getDefaultInstance()) {
						location_ = com.apple.iphone.services.LocationsProtos.WLANLocation
								.newBuilder(location_).mergeFrom(value)
								.buildPartial();
					} else {
						location_ = value;
					}
					onChanged();
				} else {
					locationBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			public Builder setChannel(int value) {
				bitField0_ |= 0x00000004;
				channel_ = value;
				onChanged();
				return this;
			}

			public Builder setLocation(
					com.apple.iphone.services.LocationsProtos.WLANLocation value) {
				if (locationBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					location_ = value;
					onChanged();
				} else {
					locationBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			public Builder setLocation(
					com.apple.iphone.services.LocationsProtos.WLANLocation.Builder builderForValue) {
				if (locationBuilder_ == null) {
					location_ = builderForValue.build();
					onChanged();
				} else {
					locationBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			void setMac(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				mac_ = value;
				onChanged();
			}

			public Builder setMac(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				mac_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:apple.ResponseWLAN)
		}

		private static final ResponseWLAN defaultInstance;

		// required string mac = 1;
		public static final int MAC_FIELD_NUMBER = 1;
		// required .apple.WLANLocation location = 2;
		public static final int LOCATION_FIELD_NUMBER = 2;

		// optional int32 channel = 21;
		public static final int CHANNEL_FIELD_NUMBER = 21;

		private int memoizedSerializedSize = -1;

		private static final long serialVersionUID = 0L;

		static {
			defaultInstance = new ResponseWLAN(true);
			defaultInstance.initFields();
		}

		public static ResponseWLAN getDefaultInstance() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_ResponseWLAN_descriptor;
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public static Builder newBuilder(
				com.apple.iphone.services.LocationsProtos.ResponseWLAN prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.ResponseWLAN parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		private int bitField0_;
		private java.lang.Object mac_;
		private com.apple.iphone.services.LocationsProtos.WLANLocation location_;

		private int channel_;

		private byte memoizedIsInitialized = -1;

		private ResponseWLAN(boolean noInit) {
		}

		// Use ResponseWLAN.newBuilder() to construct.
		private ResponseWLAN(Builder builder) {
			super(builder);
		}

		@Override
		public int getChannel() {
			return channel_;
		}

		@Override
		public ResponseWLAN getDefaultInstanceForType() {
			return defaultInstance;
		}

		@Override
		public com.apple.iphone.services.LocationsProtos.WLANLocation getLocation() {
			return location_;
		}

		@Override
		public com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder getLocationOrBuilder() {
			return location_;
		}

		@Override
		public String getMac() {
			final java.lang.Object ref = mac_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					mac_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getMacBytes() {
			final java.lang.Object ref = mac_;
			if (ref instanceof String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				mac_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getMacBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(2, location_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						21, channel_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@Override
		public boolean hasChannel() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		@Override
		public boolean hasLocation() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		@Override
		public boolean hasMac() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		private void initFields() {
			mac_ = "";
			location_ = com.apple.iphone.services.LocationsProtos.WLANLocation
					.getDefaultInstance();
			channel_ = 0;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_ResponseWLAN_fieldAccessorTable;
		}

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			if (!hasMac()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasLocation()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!getLocation().isInitialized()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getMacBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeMessage(2, location_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(21, channel_);
			}
			getUnknownFields().writeTo(output);
		}

		// @@protoc_insertion_point(class_scope:apple.ResponseWLAN)
	}

	public interface ResponseWLANOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		int getChannel();

		com.apple.iphone.services.LocationsProtos.WLANLocation getLocation();

		com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder getLocationOrBuilder();

		String getMac();

		// optional int32 channel = 21;
		boolean hasChannel();

		// required .apple.WLANLocation location = 2;
		boolean hasLocation();

		// required string mac = 1;
		boolean hasMac();
	}

	public static final class WLANLocation extends
			com.google.protobuf.GeneratedMessage implements
			WLANLocationOrBuilder {
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.apple.iphone.services.LocationsProtos.WLANLocationOrBuilder {
			private static Builder create() {
				return new Builder();
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_WLANLocation_descriptor;
			}

			private int bitField0_;

			// required int64 latitude = 1;
			private long latitude_;
			// required int64 longitude = 2;
			private long longitude_;
			// required int64 unknown3 = 3;
			private long unknown3_;

			// Construct using
			// com.apple.iphone.services.LocationsProtos.WLANLocation.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.WLANLocation build() {
				final com.apple.iphone.services.LocationsProtos.WLANLocation result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.apple.iphone.services.LocationsProtos.WLANLocation buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				final com.apple.iphone.services.LocationsProtos.WLANLocation result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.WLANLocation buildPartial() {
				final com.apple.iphone.services.LocationsProtos.WLANLocation result = new com.apple.iphone.services.LocationsProtos.WLANLocation(
						this);
				final int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.latitude_ = latitude_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.longitude_ = longitude_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.unknown3_ = unknown3_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clear() {
				super.clear();
				latitude_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				longitude_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000002);
				unknown3_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clearLatitude() {
				bitField0_ = (bitField0_ & ~0x00000001);
				latitude_ = 0L;
				onChanged();
				return this;
			}

			public Builder clearLongitude() {
				bitField0_ = (bitField0_ & ~0x00000002);
				longitude_ = 0L;
				onChanged();
				return this;
			}

			public Builder clearUnknown3() {
				bitField0_ = (bitField0_ & ~0x00000004);
				unknown3_ = 0L;
				onChanged();
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.apple.iphone.services.LocationsProtos.WLANLocation getDefaultInstanceForType() {
				return com.apple.iphone.services.LocationsProtos.WLANLocation
						.getDefaultInstance();
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.apple.iphone.services.LocationsProtos.WLANLocation
						.getDescriptor();
			}

			@Override
			public long getLatitude() {
				return latitude_;
			}

			@Override
			public long getLongitude() {
				return longitude_;
			}

			@Override
			public long getUnknown3() {
				return unknown3_;
			}

			@Override
			public boolean hasLatitude() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			@Override
			public boolean hasLongitude() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			@Override
			public boolean hasUnknown3() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.apple.iphone.services.LocationsProtos.internal_static_apple_WLANLocation_fieldAccessorTable;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasLatitude()) {

					return false;
				}
				if (!hasLongitude()) {

					return false;
				}
				if (!hasUnknown3()) {

					return false;
				}
				return true;
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			public Builder mergeFrom(
					com.apple.iphone.services.LocationsProtos.WLANLocation other) {
				if (other == com.apple.iphone.services.LocationsProtos.WLANLocation
						.getDefaultInstance()) {
					return this;
				}
				if (other.hasLatitude()) {
					setLatitude(other.getLatitude());
				}
				if (other.hasLongitude()) {
					setLongitude(other.getLongitude());
				}
				if (other.hasUnknown3()) {
					setUnknown3(other.getUnknown3());
				}
				mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				final com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(getUnknownFields());
				while (true) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						latitude_ = input.readInt64();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						longitude_ = input.readInt64();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						unknown3_ = input.readInt64();
						break;
					}
					}
				}
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.apple.iphone.services.LocationsProtos.WLANLocation) {
					return mergeFrom((com.apple.iphone.services.LocationsProtos.WLANLocation) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder setLatitude(long value) {
				bitField0_ |= 0x00000001;
				latitude_ = value;
				onChanged();
				return this;
			}

			public Builder setLongitude(long value) {
				bitField0_ |= 0x00000002;
				longitude_ = value;
				onChanged();
				return this;
			}

			public Builder setUnknown3(long value) {
				bitField0_ |= 0x00000004;
				unknown3_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:apple.WLANLocation)
		}

		private static final WLANLocation defaultInstance;

		// required int64 latitude = 1;
		public static final int LATITUDE_FIELD_NUMBER = 1;
		// required int64 longitude = 2;
		public static final int LONGITUDE_FIELD_NUMBER = 2;

		// required int64 unknown3 = 3;
		public static final int UNKNOWN3_FIELD_NUMBER = 3;

		private int memoizedSerializedSize = -1;

		private static final long serialVersionUID = 0L;

		static {
			defaultInstance = new WLANLocation(true);
			defaultInstance.initFields();
		}

		public static WLANLocation getDefaultInstance() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_WLANLocation_descriptor;
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public static Builder newBuilder(
				com.apple.iphone.services.LocationsProtos.WLANLocation prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			final Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.apple.iphone.services.LocationsProtos.WLANLocation parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		private int bitField0_;

		private long latitude_;

		private long longitude_;
		private long unknown3_;

		private byte memoizedIsInitialized = -1;

		private WLANLocation(boolean noInit) {
		}

		// Use WLANLocation.newBuilder() to construct.
		private WLANLocation(Builder builder) {
			super(builder);
		}

		@Override
		public WLANLocation getDefaultInstanceForType() {
			return defaultInstance;
		}

		@Override
		public long getLatitude() {
			return latitude_;
		}

		@Override
		public long getLongitude() {
			return longitude_;
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, latitude_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						2, longitude_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						3, unknown3_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@Override
		public long getUnknown3() {
			return unknown3_;
		}

		@Override
		public boolean hasLatitude() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		@Override
		public boolean hasLongitude() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		@Override
		public boolean hasUnknown3() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		private void initFields() {
			latitude_ = 0L;
			longitude_ = 0L;
			unknown3_ = 0L;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.apple.iphone.services.LocationsProtos.internal_static_apple_WLANLocation_fieldAccessorTable;
		}

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			if (!hasLatitude()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasLongitude()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasUnknown3()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, latitude_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt64(2, longitude_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt64(3, unknown3_);
			}
			getUnknownFields().writeTo(output);
		}

		// @@protoc_insertion_point(class_scope:apple.WLANLocation)
	}

	public interface WLANLocationOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		long getLatitude();

		long getLongitude();

		long getUnknown3();

		// required int64 latitude = 1;
		boolean hasLatitude();

		// required int64 longitude = 2;
		boolean hasLongitude();

		// required int64 unknown3 = 3;
		boolean hasUnknown3();
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_apple_Response_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_apple_Response_fieldAccessorTable;

	private static com.google.protobuf.Descriptors.Descriptor internal_static_apple_WLANLocation_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_apple_WLANLocation_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_apple_ResponseWLAN_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_apple_ResponseWLAN_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_apple_RequestWLAN_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_apple_RequestWLAN_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_apple_Request_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_apple_Request_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		final java.lang.String[] descriptorData = { "\n\017apple_loc.proto\022\005apple\"-\n\010Response\022!\n\004"
				+ "wlan\030\002 \003(\0132\023.apple.ResponseWLAN\"E\n\014WLANL"
				+ "ocation\022\020\n\010latitude\030\001 \002(\003\022\021\n\tlongitude\030\002"
				+ " \002(\003\022\020\n\010unknown3\030\003 \002(\003\"S\n\014ResponseWLAN\022\013"
				+ "\n\003mac\030\001 \002(\t\022%\n\010location\030\002 \002(\0132\023.apple.WL"
				+ "ANLocation\022\017\n\007channel\030\025 \001(\005\"\032\n\013RequestWL"
				+ "AN\022\013\n\003mac\030\001 \002(\t\"_\n\007Request\022 \n\004wlan\030\002 \003(\013"
				+ "2\022.apple.RequestWLAN\022\020\n\010unknown3\030\003 \002(\005\022\020"
				+ "\n\010unknown4\030\004 \002(\005\022\016\n\006source\030\005 \002(\tB,\n\031com."
				+ "apple.iphone.servicesB\017LocationsProtos" };
		final com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			@Override
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_apple_Response_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_apple_Response_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_apple_Response_descriptor,
						new java.lang.String[] { "Wlan", },
						com.apple.iphone.services.LocationsProtos.Response.class,
						com.apple.iphone.services.LocationsProtos.Response.Builder.class);
				internal_static_apple_WLANLocation_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_apple_WLANLocation_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_apple_WLANLocation_descriptor,
						new java.lang.String[] { "Latitude", "Longitude",
								"Unknown3", },
						com.apple.iphone.services.LocationsProtos.WLANLocation.class,
						com.apple.iphone.services.LocationsProtos.WLANLocation.Builder.class);
				internal_static_apple_ResponseWLAN_descriptor = getDescriptor()
						.getMessageTypes().get(2);
				internal_static_apple_ResponseWLAN_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_apple_ResponseWLAN_descriptor,
						new java.lang.String[] { "Mac", "Location", "Channel", },
						com.apple.iphone.services.LocationsProtos.ResponseWLAN.class,
						com.apple.iphone.services.LocationsProtos.ResponseWLAN.Builder.class);
				internal_static_apple_RequestWLAN_descriptor = getDescriptor()
						.getMessageTypes().get(3);
				internal_static_apple_RequestWLAN_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_apple_RequestWLAN_descriptor,
						new java.lang.String[] { "Mac", },
						com.apple.iphone.services.LocationsProtos.RequestWLAN.class,
						com.apple.iphone.services.LocationsProtos.RequestWLAN.Builder.class);
				internal_static_apple_Request_descriptor = getDescriptor()
						.getMessageTypes().get(4);
				internal_static_apple_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_apple_Request_descriptor,
						new java.lang.String[] { "Wlan", "Unknown3",
								"Unknown4", "Source", },
						com.apple.iphone.services.LocationsProtos.Request.class,
						com.apple.iphone.services.LocationsProtos.Request.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	private LocationsProtos() {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
